ALTER TABLE user_bots ADD COLUMN IF NOT EXISTS support_server_url TEXT;
ALTER TABLE user_bots ADD COLUMN IF NOT EXISTS unlocked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_bots ADD COLUMN IF NOT EXISTS unlocked_at TIMESTAMPTZ;
